name: Hello World!

on:
  push:
    branches:
      - main

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    steps:
      - name: Echo Hello
        run: |
          echo "Hello World!"
          echo "Hello World Again!"
      - name: Current Time
        run: date
      - name: Current Directory
        run: ls -l
